controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_1_joint
      - upper_1_joint
      - lower_1_joint
      - lower_2_joint
      - ee_pitch_joint
      - ee_roll_joint
  - name: fake_gripper_controller
    joints:
      - end_effector_joint